version: "3.7"
services:
  frontend:
    container_name: frontend-calendar
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    volumes:
      - ".:/usr/app"
      - "/usr/app/packages/shared/node_modules"
      - "/usr/app/packages/frontend/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3333:3000
    stdin_open: true
