FROM node:16.13.0-alpine
ENV NODE_ENV=development
RUN yarn global add typescript
WORKDIR /usr/shared/
COPY ./packages/shared/package.json .
RUN yarn install
COPY ./packages/shared/ .
WORKDIR /usr/frontend/
RUN pwd
RUN ls
ENV PATH /usr/frontend/node_modules/.bin:$PATH
COPY ./packages/frontend/package.json .
RUN yarn install \
    && yarn add react-scripts@4.0.3 -g
COPY ./packages/frontend/ .
EXPOSE 3000
CMD ["yarn", "start"]
