FROM node:14 as builder
ENV NODE_ENV=development
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn global add typescript
WORKDIR /usr/shared/
COPY ./packages/shared/package.json .
RUN yarn install
COPY ./packages/shared/ .
WORKDIR /usr/app/
COPY ./packages/frontend/package.json .
RUN yarn install \
    && yarn add react-scripts@4.0.3 -g
COPY ./packages/frontend/ .
EXPOSE 3000
CMD ["npm", "start"]
