FROM node:16.13.0-alpine
ENV NODE_ENV=development
ENV PATH /usr/app/frontend/node_modules/.bin:$PATH
RUN yarn global add typescript
WORKDIR /usr/app
COPY . .
RUN yarn workspace @calendar/shared install
RUN yarn workspace frontend install
EXPOSE 3000
CMD ["yarn", "workspace", "frontend", "start"]
