version: "3.7"
services:
  frontend:
    container_name: frontend-calendar
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3333:3000
    volumes:
      - ./packages:/usr/
      - /usr/shared/node_modules
      - /usr/app/node_modules
    stdin_open: true

  backend:
    container_name: backend-calendar
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.back.dev

    volumes:
      - ./packages/backend:/usr/app
      - /usr/app/node_modules
